### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by frnkvieira** [cybermatt/fast-luhn#1]
```
pip3 install fast-luhn
ERROR: Could not find a version that satisfies the requirement fast-luhn (from versions: none)
ERROR: No matching distribution found for fast-luhn
```

It would be nice to publish wheels to Python 3.8
Anyway, thanks for the great work :)

**Comment by alittlesliceoftom** [comment]
Same issue on 3.7 inside Conda: 
pip install fast-luhn
ERROR: Could not find a version that satisfies the requirement fast-luhn (from versions: none)
ERROR: No matching distribution found for fast-luhn

**Comment by taomanwai** [comment]
Same here

**Comment by allyo-dmytro-smyk** [comment]
Same here. @cybermatt can you check this please?

**Comment by cybermatt** [comment]
Fixed in 0.1.5 version

**Comment by frnkvieira** [comment]
It now works on Python 3.8 and Python 3.9.
Thanks @cybermatt

**Comment by Git-Romer** [comment]
Having the same issue using Python 3.9.5 
Am I doing something wrong?
```
$ pip install fast-luhn 
ERROR: Could not find a version that satisfies the requirement fast-luhn (from versions: none)
ERROR: No matching distribution found for fast-luhn
```

**Comment by helixphoenix** [comment]
I am having the same issue at version python3.8.2 and v.0.1.5
ERROR: Could not find a version that satisfies the requirement fast-luhn (from versions: none)
ERROR: No matching distribution found for fast-luhn

**Comment by cp-org** [comment]
Same installation error on Python 3.9.6
